version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DB_HOST=user-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_service
      - DB_PORT=5432
    env_file:
      - .env

  user-db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service
    ports:
      - "5433:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  user_postgres_data:
